[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gaze-estimation"
version = "0.1.0"
description = "python gaze estimation with OpenVINO"
authors = [
    { name="Omri" }
]
dependencies = [
    "opencv-python",
    "openvino-dev",
]